### ISSUE TITLE
Duplicate predicted publications

### ISSUE THREAD

**Issue by lizgzil** [wellcometrust/policytool#141] opened 2019-05-10 11:19 UTC
We have noticed that in parser_references/document we see lots of duplicated data.

Size of parser_references/document = 5,228,096
We would want this number to mean there are 5,228,096 references found in all the scraped documents, but we find duplicates amongst this.

## Are there duplicates?
Yes, there are many, whether we remove title=Null or not. In one case, from the same policy document we saw 837 references with the same title.
![Screenshot 2019-05-10 at 11 30 14](https://user-images.githubusercontent.com/15956065/57522964-87226400-731b-11e9-92d5-5c867f10b8f1.png)
![Screenshot 2019-05-10 at 11 32 41](https://user-images.githubusercontent.com/15956065/57522965-88ec2780-731b-11e9-8d60-55065fdc6e95.png)

## Are the duplicated data added on different dates?
There are different dates, but duplicates for each of these dates.
e.g. for this policy document and title combination there are 9 creation dates each with 93 duplicates in  
![Screenshot 2019-05-10 at 12 12 10](https://user-images.githubusercontent.com/15956065/57523435-e3d24e80-731c-11e9-8656-c38e4defd897.png)

## How many references are there if we remove duplicate title-file_hash?
946,372
![Screenshot 2019-05-10 at 12 15 35](https://user-images.githubusercontent.com/15956065/57523617-5b07e280-731d-11e9-89eb-318e4b8ed3c0.png)

## How many references are there if we remove duplicate title-journal-authors-etc...-file_hash?
1,131,210
![Screenshot 2019-05-10 at 12 05 15](https://user-images.githubusercontent.com/15956065/57523507-0f553900-731d-11e9-8efc-4e77f9bcb29d.png)

## Next steps
Investigation into whether this is a bug in the algorithm or the database needs to be checked out.

There are several other issues which point towards duplicated data in the database (https://github.com/wellcometrust/policytool/issues/48, https://github.com/wellcometrust/policytool/issues/104).

**Comment by lizgzil** [comment] 2019-05-10 11:28
There are 1,447,317 rows in parser_references/document which are Null for all the predicted components.
![Screenshot 2019-05-10 at 12 26 45](https://user-images.githubusercontent.com/15956065/57524247-272dbc80-731f-11e9-9950-e2544da1a7f4.png)

**Comment by nsorros** [comment] 2019-05-10 12:51
Thanks @lizgzil for the detailed issue.

@hblanks and @SamDepardieu It is slightly important we have a chat about this and come up with a plan to investigate as this problem comes up every time someone asks for data from the policy tool almost.

It is important to understand whether that is being caused by how we parse and match or how we save in the database so it would be good to ask tasks for both data science and engineering to investigate the relevant parts. Let's have a chat on Monday before weekly planning.

**Comment by nsorros** [comment] 2019-05-13 08:47
Closing this as @hblanks suggested. Will leave him to give more info on the decision if he wants.

**Closed by nsorros** 2019-05-13 08:47 UTC
Labels: bug
