### ISSUE TITLE
Code examples in README.md don't work

### ISSUE THREAD

**Issue by peter337** [wellcometrust/policytool#71] opened 2019-02-15 11:29 UTC
Came across a couple of errors when testing the code in the README.

1. Under method 3 and 4, using ```--num-workers None``` returns ```error: argument --num-workers: invalid int value: 'None'```.

I think this is because of create_argparser in refparse.py, which tries to coerce 'None' to 'int'.

2. Under method 4, running ```python parse_latest.py msf``` returns ```Output url should start with 'file://'```.

I think this is because of a combination of: the if statement in parse_latest.py requiring output_url to start with 'file://'; and the default for output_url in settings.py beginning with 'postgresql+psycopg2://'.

**Comment by lizgzil** [comment] 2019-02-15 11:35
This is a duplicate of https://github.com/wellcometrust/policytool/issues/67, but please add these comments to it. It'd be useful to know if the fixes I suggest in that issue make the code work for you too.

**Closed** 2019-02-15 11:38 UTC

**Comment by lizgzil** [comment] 2019-02-15 11:42
I should have assigned you to it so you could see the fixes, my bad.
